
name: .NET Core

on:      
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src
      VERSION: 5.4.0-preview.1

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.101
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run:  dotnet restore 
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Testing
      run: dotnet test
      working-directory: ${{env.working-directory}}
